// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Softwareschmiede.Infrastructure.Data;

#nullable disable

namespace Softwareschmiede.Migrations
{
    [DbContext(typeof(SoftwareschmiededDbContext))]
    [Migration("20260506195327_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.15");

            modelBuilder.Entity("Softwareschmiede.Domain.Entities.Aufgabe", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("AbschlussDatum")
                        .HasColumnType("TEXT");

                    b.Property<string>("AgentenName")
                        .HasColumnType("TEXT");

                    b.Property<string>("AgentenpaketName")
                        .HasColumnType("TEXT");

                    b.Property<string>("AnforderungsBeschreibung")
                        .HasColumnType("TEXT");

                    b.Property<string>("BranchName")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("ErstellungsDatum")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("GitRepositoryId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LokalerKlonPfad")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProjektId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Titel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GitRepositoryId");

                    b.HasIndex("ProjektId");

                    b.ToTable("Aufgaben");
                });

            modelBuilder.Entity("Softwareschmiede.Domain.Entities.GitRepository", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Aktiv")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PluginTyp")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProjektId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RepositoryName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RepositoryUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProjektId");

                    b.ToTable("GitRepositories");
                });

            modelBuilder.Entity("Softwareschmiede.Domain.Entities.IssueReferenz", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AufgabeId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Body")
                        .HasColumnType("TEXT");

                    b.Property<int?>("IssueNummer")
                        .HasColumnType("INTEGER");

                    b.Property<string>("IssueUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("LabelsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Milestone")
                        .HasColumnType("TEXT");

                    b.Property<string>("Titel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AufgabeId")
                        .IsUnique();

                    b.ToTable("IssueReferenzen");
                });

            modelBuilder.Entity("Softwareschmiede.Domain.Entities.PluginKonfiguration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Aktiviert")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AnzeigeName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("BaseUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("CredentialStoreKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PluginKategorie")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PluginTyp")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("PluginKonfigurationen");
                });

            modelBuilder.Entity("Softwareschmiede.Domain.Entities.Projekt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Beschreibung")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("ErstellungsDatum")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Projekte");
                });

            modelBuilder.Entity("Softwareschmiede.Domain.Entities.Protokolleintrag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AgentName")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AufgabeId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Inhalt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Typ")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("Zeitstempel")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AufgabeId");

                    b.ToTable("Protokolleintraege");
                });

            modelBuilder.Entity("Softwareschmiede.Domain.Entities.TestErgebnis", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long>("Dauer")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Fehlermeldung")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProtokollEintragId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TestName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProtokollEintragId");

                    b.ToTable("TestErgebnisse");
                });

            modelBuilder.Entity("Softwareschmiede.Domain.Entities.Aufgabe", b =>
                {
                    b.HasOne("Softwareschmiede.Domain.Entities.GitRepository", "GitRepository")
                        .WithMany()
                        .HasForeignKey("GitRepositoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Softwareschmiede.Domain.Entities.Projekt", "Projekt")
                        .WithMany("Aufgaben")
                        .HasForeignKey("ProjektId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GitRepository");

                    b.Navigation("Projekt");
                });

            modelBuilder.Entity("Softwareschmiede.Domain.Entities.GitRepository", b =>
                {
                    b.HasOne("Softwareschmiede.Domain.Entities.Projekt", "Projekt")
                        .WithMany("Repositories")
                        .HasForeignKey("ProjektId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Projekt");
                });

            modelBuilder.Entity("Softwareschmiede.Domain.Entities.IssueReferenz", b =>
                {
                    b.HasOne("Softwareschmiede.Domain.Entities.Aufgabe", "Aufgabe")
                        .WithOne("IssueReferenz")
                        .HasForeignKey("Softwareschmiede.Domain.Entities.IssueReferenz", "AufgabeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Aufgabe");
                });

            modelBuilder.Entity("Softwareschmiede.Domain.Entities.Protokolleintrag", b =>
                {
                    b.HasOne("Softwareschmiede.Domain.Entities.Aufgabe", "Aufgabe")
                        .WithMany("Protokolleintraege")
                        .HasForeignKey("AufgabeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Aufgabe");
                });

            modelBuilder.Entity("Softwareschmiede.Domain.Entities.TestErgebnis", b =>
                {
                    b.HasOne("Softwareschmiede.Domain.Entities.Protokolleintrag", "Protokolleintrag")
                        .WithMany("TestErgebnisse")
                        .HasForeignKey("ProtokollEintragId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Protokolleintrag");
                });

            modelBuilder.Entity("Softwareschmiede.Domain.Entities.Aufgabe", b =>
                {
                    b.Navigation("IssueReferenz");

                    b.Navigation("Protokolleintraege");
                });

            modelBuilder.Entity("Softwareschmiede.Domain.Entities.Projekt", b =>
                {
                    b.Navigation("Aufgaben");

                    b.Navigation("Repositories");
                });

            modelBuilder.Entity("Softwareschmiede.Domain.Entities.Protokolleintrag", b =>
                {
                    b.Navigation("TestErgebnisse");
                });
#pragma warning restore 612, 618
        }
    }
}
