// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Softwareschmiede.Infrastructure.Data;

#nullable disable

namespace Softwareschmiede.Migrations
{
    [DbContext(typeof(SoftwareschmiededDbContext))]
    [Migration("20260616112522_202606160001_SimplifyAufgabeStatusEnum")]
    partial class _202606160001_SimplifyAufgabeStatusEnum
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.17");

            modelBuilder.Entity("Softwareschmiede.Domain.Entities.AppEinstellung", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long>("AktualisiertAm")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Schluessel")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Wert")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Schluessel")
                        .IsUnique();

                    b.ToTable("AppEinstellungen");
                });

            modelBuilder.Entity("Softwareschmiede.Domain.Entities.Aufgabe", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long?>("AbschlussDatum")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AgentenName")
                        .HasColumnType("TEXT");

                    b.Property<string>("AgentenpaketName")
                        .HasColumnType("TEXT");

                    b.Property<string>("AktiveRunId")
                        .HasColumnType("TEXT");

                    b.Property<string>("AnforderungsBeschreibung")
                        .HasColumnType("TEXT");

                    b.Property<string>("BranchName")
                        .HasColumnType("TEXT");

                    b.Property<long>("ErstellungsDatum")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("GitRepositoryId")
                        .HasColumnType("TEXT");

                    b.Property<string>("KiPluginPrefix")
                        .HasColumnType("TEXT");

                    b.Property<long?>("LastHeartbeatUtc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LokalerKlonPfad")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProjektId")
                        .HasColumnType("TEXT");

                    b.Property<int>("RecoveryVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Titel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long?>("VorschlagAusfuehrenAbUtc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("VorschlagPrompt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GitRepositoryId");

                    b.HasIndex("ProjektId");

                    b.ToTable("Aufgaben");
                });

            modelBuilder.Entity("Softwareschmiede.Domain.Entities.BenachrichtigungsAudioDatei", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("BenutzerId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("GroesseBytes")
                        .HasColumnType("INTEGER");

                    b.Property<long>("HochgeladenAm")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("Inhalt")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalDateiname")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BenutzerId")
                        .IsUnique();

                    b.ToTable("BenachrichtigungsAudioDateien");
                });

            modelBuilder.Entity("Softwareschmiede.Domain.Entities.BenachrichtigungsDispatchLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AufgabeId")
                        .HasColumnType("TEXT");

                    b.Property<string>("BenutzerId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Entscheidung")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EreignisId")
                        .HasColumnType("TEXT");

                    b.Property<long>("ErstelltAm")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Grund")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Kanal")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Modus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AufgabeId");

                    b.HasIndex("ErstelltAm");

                    b.HasIndex("EreignisId", "BenutzerId", "Kanal")
                        .IsUnique();

                    b.ToTable("BenachrichtigungsDispatchLogs");
                });

            modelBuilder.Entity("Softwareschmiede.Domain.Entities.BenachrichtigungsEinstellung", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long>("AktualisiertAm")
                        .HasColumnType("INTEGER");

                    b.Property<string>("BannerModus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("BenutzerId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("TonModus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BenutzerId")
                        .IsUnique();

                    b.ToTable("BenachrichtigungsEinstellungen");
                });

            modelBuilder.Entity("Softwareschmiede.Domain.Entities.DiffBlock", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("BlockSequence")
                        .HasColumnType("INTEGER");

                    b.Property<string>("BlockType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DiffResultId")
                        .HasColumnType("TEXT");

                    b.Property<int>("SourceEndLine")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SourceStartLine")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TargetEndLine")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TargetStartLine")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DiffResultId");

                    b.HasIndex("DiffResultId", "BlockSequence");

                    b.ToTable("DiffBlocks");
                });

            modelBuilder.Entity("Softwareschmiede.Domain.Entities.DiffCache", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CacheKey")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<long>("CachedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CachedData")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CachingStrategy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DiffResultId")
                        .HasColumnType("TEXT");

                    b.Property<long>("ExpiresAt")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsValid")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CacheKey")
                        .IsUnique();

                    b.HasIndex("DiffResultId")
                        .IsUnique();

                    b.HasIndex("ExpiresAt");

                    b.ToTable("DiffCaches");
                });

            modelBuilder.Entity("Softwareschmiede.Domain.Entities.DiffLine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DiffBlockId")
                        .HasColumnType("TEXT");

                    b.Property<int>("LineSequence")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LineStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("SourceLineNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TargetLineNumber")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DiffBlockId");

                    b.HasIndex("DiffBlockId", "LineSequence");

                    b.ToTable("DiffLines");
                });

            modelBuilder.Entity("Softwareschmiede.Domain.Entities.DiffResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("AddedLines")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("AufgabeId")
                        .HasColumnType("TEXT");

                    b.Property<string>("DiffType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long?>("ExpiresAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<long>("GeneratedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GeneratedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("GitRepositoryId")
                        .HasColumnType("TEXT");

                    b.Property<int>("LineCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ModifiedLines")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("ProtokollEintragId")
                        .HasColumnType("TEXT");

                    b.Property<int>("RemovedLines")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourceContent")
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceVersion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetContent")
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetVersion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AufgabeId");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("GitRepositoryId");

                    b.HasIndex("ProtokollEintragId")
                        .IsUnique();

                    b.HasIndex("Status");

                    b.HasIndex("AufgabeId", "FilePath");

                    b.ToTable("DiffResults");
                });

            modelBuilder.Entity("Softwareschmiede.Domain.Entities.GitRepository", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Aktiv")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PluginTyp")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProjektId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RepositoryName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RepositoryUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProjektId");

                    b.ToTable("GitRepositories");
                });

            modelBuilder.Entity("Softwareschmiede.Domain.Entities.IssueReferenz", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AufgabeId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Body")
                        .HasColumnType("TEXT");

                    b.Property<int?>("IssueNummer")
                        .HasColumnType("INTEGER");

                    b.Property<string>("IssueUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("LabelsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Milestone")
                        .HasColumnType("TEXT");

                    b.Property<string>("Titel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AufgabeId")
                        .IsUnique();

                    b.ToTable("IssueReferenzen");
                });

            modelBuilder.Entity("Softwareschmiede.Domain.Entities.PluginKonfiguration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Aktiviert")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AnzeigeName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("BaseUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("CredentialStoreKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PluginKategorie")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PluginTyp")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("PluginKonfigurationen");
                });

            modelBuilder.Entity("Softwareschmiede.Domain.Entities.Projekt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Beschreibung")
                        .HasColumnType("TEXT");

                    b.Property<long>("ErstellungsDatum")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Projekte");
                });

            modelBuilder.Entity("Softwareschmiede.Domain.Entities.Protokolleintrag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AgentName")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AufgabeId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Inhalt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Typ")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("Zeitstempel")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AufgabeId");

                    b.ToTable("Protokolleintraege");
                });

            modelBuilder.Entity("Softwareschmiede.Domain.Entities.RepositoryStartKonfiguration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Aktiv")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("GitRepositoryId")
                        .HasColumnType("TEXT");

                    b.Property<string>("StartScriptRelativePath")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GitRepositoryId")
                        .IsUnique();

                    b.ToTable("RepositoryStartKonfigurationen");
                });

            modelBuilder.Entity("Softwareschmiede.Domain.Entities.TestErgebnis", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long>("Dauer")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Fehlermeldung")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProtokollEintragId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TestName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProtokollEintragId");

                    b.ToTable("TestErgebnisse");
                });

            modelBuilder.Entity("Softwareschmiede.Domain.Entities.Aufgabe", b =>
                {
                    b.HasOne("Softwareschmiede.Domain.Entities.GitRepository", "GitRepository")
                        .WithMany()
                        .HasForeignKey("GitRepositoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Softwareschmiede.Domain.Entities.Projekt", "Projekt")
                        .WithMany("Aufgaben")
                        .HasForeignKey("ProjektId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GitRepository");

                    b.Navigation("Projekt");
                });

            modelBuilder.Entity("Softwareschmiede.Domain.Entities.DiffBlock", b =>
                {
                    b.HasOne("Softwareschmiede.Domain.Entities.DiffResult", "DiffResult")
                        .WithMany("DiffBlocks")
                        .HasForeignKey("DiffResultId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DiffResult");
                });

            modelBuilder.Entity("Softwareschmiede.Domain.Entities.DiffCache", b =>
                {
                    b.HasOne("Softwareschmiede.Domain.Entities.DiffResult", "DiffResult")
                        .WithOne("DiffCache")
                        .HasForeignKey("Softwareschmiede.Domain.Entities.DiffCache", "DiffResultId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DiffResult");
                });

            modelBuilder.Entity("Softwareschmiede.Domain.Entities.DiffLine", b =>
                {
                    b.HasOne("Softwareschmiede.Domain.Entities.DiffBlock", "DiffBlock")
                        .WithMany("DiffLines")
                        .HasForeignKey("DiffBlockId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DiffBlock");
                });

            modelBuilder.Entity("Softwareschmiede.Domain.Entities.DiffResult", b =>
                {
                    b.HasOne("Softwareschmiede.Domain.Entities.Aufgabe", "Aufgabe")
                        .WithMany("DiffResults")
                        .HasForeignKey("AufgabeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Softwareschmiede.Domain.Entities.GitRepository", "GitRepository")
                        .WithMany("DiffResults")
                        .HasForeignKey("GitRepositoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Softwareschmiede.Domain.Entities.Protokolleintrag", "ProtokollEintrag")
                        .WithOne("DiffResult")
                        .HasForeignKey("Softwareschmiede.Domain.Entities.DiffResult", "ProtokollEintragId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Aufgabe");

                    b.Navigation("GitRepository");

                    b.Navigation("ProtokollEintrag");
                });

            modelBuilder.Entity("Softwareschmiede.Domain.Entities.GitRepository", b =>
                {
                    b.HasOne("Softwareschmiede.Domain.Entities.Projekt", "Projekt")
                        .WithMany("Repositories")
                        .HasForeignKey("ProjektId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Projekt");
                });

            modelBuilder.Entity("Softwareschmiede.Domain.Entities.IssueReferenz", b =>
                {
                    b.HasOne("Softwareschmiede.Domain.Entities.Aufgabe", "Aufgabe")
                        .WithOne("IssueReferenz")
                        .HasForeignKey("Softwareschmiede.Domain.Entities.IssueReferenz", "AufgabeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Aufgabe");
                });

            modelBuilder.Entity("Softwareschmiede.Domain.Entities.Protokolleintrag", b =>
                {
                    b.HasOne("Softwareschmiede.Domain.Entities.Aufgabe", "Aufgabe")
                        .WithMany("Protokolleintraege")
                        .HasForeignKey("AufgabeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Aufgabe");
                });

            modelBuilder.Entity("Softwareschmiede.Domain.Entities.RepositoryStartKonfiguration", b =>
                {
                    b.HasOne("Softwareschmiede.Domain.Entities.GitRepository", "GitRepository")
                        .WithOne("StartKonfiguration")
                        .HasForeignKey("Softwareschmiede.Domain.Entities.RepositoryStartKonfiguration", "GitRepositoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GitRepository");
                });

            modelBuilder.Entity("Softwareschmiede.Domain.Entities.TestErgebnis", b =>
                {
                    b.HasOne("Softwareschmiede.Domain.Entities.Protokolleintrag", "Protokolleintrag")
                        .WithMany("TestErgebnisse")
                        .HasForeignKey("ProtokollEintragId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Protokolleintrag");
                });

            modelBuilder.Entity("Softwareschmiede.Domain.Entities.Aufgabe", b =>
                {
                    b.Navigation("DiffResults");

                    b.Navigation("IssueReferenz");

                    b.Navigation("Protokolleintraege");
                });

            modelBuilder.Entity("Softwareschmiede.Domain.Entities.DiffBlock", b =>
                {
                    b.Navigation("DiffLines");
                });

            modelBuilder.Entity("Softwareschmiede.Domain.Entities.DiffResult", b =>
                {
                    b.Navigation("DiffBlocks");

                    b.Navigation("DiffCache");
                });

            modelBuilder.Entity("Softwareschmiede.Domain.Entities.GitRepository", b =>
                {
                    b.Navigation("DiffResults");

                    b.Navigation("StartKonfiguration");
                });

            modelBuilder.Entity("Softwareschmiede.Domain.Entities.Projekt", b =>
                {
                    b.Navigation("Aufgaben");

                    b.Navigation("Repositories");
                });

            modelBuilder.Entity("Softwareschmiede.Domain.Entities.Protokolleintrag", b =>
                {
                    b.Navigation("DiffResult");

                    b.Navigation("TestErgebnisse");
                });
#pragma warning restore 612, 618
        }
    }
}
